# -*- coding: utf-8 -*-
"""Clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h4tyWhmysMfadaUCrqvrvA7jY3IUwxhg

INTELGENCIA COMPUTACIONAL

INTEGRANTES:

YESENIA MEDINA TICONA

LEYDI VERONICA PACSI QUISPECONDORI

DANNY CONDORI LUJANO

En este ejemplo de Clustering se desarrollara con un dataset ("movies.csv" que contiene dos tipos de datos que son numero de likes y puntaje dado por pelicula

Importamos Librerias
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

"""Extraemos los datos de nuestro dataset ("movies.csv")"""

datos=pd.read_csv('moviescs.csv')
df=pd.DataFrame(datos)
df

"""Extraemos los valores de x y y"""

x=df['cast_total_facebook_likes'].values
y=df['imdb_score'].values
print("Valor maximo de likes: ",df['cast_total_facebook_likes'].max())
print("Valor promedio de likes: ",df['cast_total_facebook_likes'].mean())
print("Valor minimo de likes: ",df['cast_total_facebook_likes'].min())

"""Decalramos un array de array"""

X=np.array(list(zip(x,y)))
print(X)

"""Definimos el número de clusters y ajustamos los datos y asignamos etiquetas a los datos agrupados"""

Kmeans=KMeans(n_clusters=2)
Kmeans=Kmeans.fit(X)
labels=Kmeans.predict(X)
centroids=Kmeans.cluster_centers_

colors=["m.","r.","c.","y.","b."]

for i in range(len(X)):
    print("Coordenada: ",X[i],"Label: ",labels[i])
    plt.plot(X[i][0],X[i][1],colors[labels[i]],markersize=10)
plt.scatter(centroids[:,0],centroids[:,1],marker='x',s=150,linewidths=5,zorder=10)
plt.show()