# -*- coding: utf-8 -*-
"""RDimen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y0-LXC6PXrWuHUQtmhrvIdluOMxLm5jr

INTELGENCIA COMPUTACIONAL

INTEGRANTES:

YESENIA MEDINA TICONA

LEYDI VERONICA PACSI QUISPECONDORI

DANNY CONDORI LUJANO

En este ejemplo de Reduccion de Dimensionalidad se desarrollara con una base de datos de Iris aplicando la Reduccion de DImensionalidad

Importamos las librerias requeridas para desarrollar la reduccion de dimensionalidad
"""

# Commented out IPython magic to ensure Python compatibility.

import pandas as pd
from sklearn.manifold import TSNE
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import pylab as pl
import matplotlib.pyplot as plt
from itertools import cycle
# %matplotlib inline

"""Extraemos los datos del dataset ("Iris.csv")"""

datos=pd.read_csv('Iris.csv')
df=pd.DataFrame(datos)
df

"""Estandarizamos todas nuestras variables para que esten en la misma escala antes de aplicar PCA y T-sne"""

from sklearn.preprocessing import StandardScaler
variables = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
x = df.loc[:, variables].values
y = df.loc[:,['Species']].values
x = StandardScaler().fit_transform(x)
x = pd.DataFrame(x)

from sklearn.decomposition import PCA
pca = PCA()
x_pca = pca.fit_transform(x)
x_pca = pd.DataFrame(x_pca)
x_pca.head()

explained_variance = pca.explained_variance_ratio_
explained_variance

x_pca['Species']=y
x_pca.columns = ['‘PC1’','’PC2','’PC3','’PC4','species']
x_pca.head()

"""Utilización de la técnica de t-SNE  con el conjunto de datos de iris."""

iris = load_iris()
X_tsne = TSNE(learning_rate=100).fit_transform(iris.data)
X_pca = PCA().fit_transform(iris.data)
plt.figure(figsize=(10, 5))
plt.subplot(121)
plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=iris.target)
plt.subplot(122)
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=iris.target)